/**
* @File Name : FieldSetController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : February 23, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | February 23, 2025 |   | Initial Version
**/

public class FieldSetController {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}